#include "ships/bastion.hpp"

#include "raymath.h"
#include <array>
#include <cmath>

// Generated by tools/svg_to_ship.py from a hand-drawn pixel-art SVG, then wired up here.
// Regenerate with: python3 tools/svg_to_ship.py yourfile.svg
void drawBastionHull(Vector2 p, float r, float angle, Color shipColor)
{
    const auto rotate = [angle](Vector2 v) -> Vector2
    {
        const float cosA = std::cos(angle);
        const float sinA = std::sin(angle);
        return Vector2{.x = v.x * cosA - v.y * sinA, .y = v.x * sinA + v.y * cosA};
    };
    const auto at = [&](float x, float y) -> Vector2
    {
        return Vector2Add(p, rotate(Vector2{.x = x * r, .y = y * r}));
    };
    (void)shipColor; // hull uses its own fixed pixel-art palette, not the ship's tint color

    {
        const Color shapeColor0 = Color{.r = 58, .g = 74, .b = 102, .a = 255};
        const std::array<Vector2, 39> shape0 = {
            at(-1.000F, -0.700F),
            at(-0.800F, -0.500F),
            at(-0.800F, -0.400F),
            at(-0.200F, -0.900F),
            at(0.200F, -0.900F),
            at(0.800F, -0.400F),
            at(0.800F, -0.500F),
            at(1.000F, -0.700F),
            at(1.000F, -0.200F),
            at(1.400F, 0.200F),
            at(1.400F, 0.800F),
            at(1.300F, 0.800F),
            at(1.200F, 0.700F),
            at(1.000F, 0.700F),
            at(0.900F, 0.600F),
            at(0.800F, 0.600F),
            at(0.600F, 0.400F),
            at(0.500F, 0.400F),
            at(0.400F, 0.300F),
            at(0.200F, 0.300F),
            at(0.200F, 0.400F),
            at(0.300F, 0.500F),
            at(0.200F, 0.500F),
            at(0.000F, 0.700F),
            at(-0.200F, 0.500F),
            at(-0.300F, 0.500F),
            at(-0.200F, 0.400F),
            at(-0.200F, 0.300F),
            at(-0.400F, 0.300F),
            at(-0.500F, 0.400F),
            at(-0.600F, 0.400F),
            at(-0.800F, 0.600F),
            at(-0.900F, 0.600F),
            at(-1.000F, 0.700F),
            at(-1.200F, 0.700F),
            at(-1.300F, 0.800F),
            at(-1.400F, 0.800F),
            at(-1.400F, 0.200F),
            at(-1.000F, -0.200F),
        };
        DrawTriangle(shape0[38], shape0[37], shape0[36], shapeColor0);
        DrawTriangle(shape0[38], shape0[36], shape0[35], shapeColor0);
        DrawTriangle(shape0[38], shape0[35], shape0[34], shapeColor0);
        DrawTriangle(shape0[38], shape0[34], shape0[33], shapeColor0);
        DrawTriangle(shape0[38], shape0[33], shape0[32], shapeColor0);
        DrawTriangle(shape0[0], shape0[38], shape0[32], shapeColor0);
        DrawTriangle(shape0[0], shape0[32], shape0[31], shapeColor0);
        DrawTriangle(shape0[0], shape0[31], shape0[30], shapeColor0);
        DrawTriangle(shape0[0], shape0[30], shape0[29], shapeColor0);
        DrawTriangle(shape0[0], shape0[29], shape0[28], shapeColor0);
        DrawTriangle(shape0[26], shape0[25], shape0[24], shapeColor0);
        DrawTriangle(shape0[26], shape0[24], shape0[23], shapeColor0);
        DrawTriangle(shape0[27], shape0[26], shape0[23], shapeColor0);
        DrawTriangle(shape0[27], shape0[23], shape0[22], shapeColor0);
        DrawTriangle(shape0[27], shape0[22], shape0[21], shapeColor0);
        DrawTriangle(shape0[27], shape0[21], shape0[20], shapeColor0);
        DrawTriangle(shape0[27], shape0[20], shape0[19], shapeColor0);
        DrawTriangle(shape0[18], shape0[17], shape0[16], shapeColor0);
        DrawTriangle(shape0[16], shape0[15], shape0[14], shapeColor0);
        DrawTriangle(shape0[14], shape0[13], shape0[12], shapeColor0);
        DrawTriangle(shape0[16], shape0[14], shape0[12], shapeColor0);
        DrawTriangle(shape0[12], shape0[11], shape0[10], shapeColor0);
        DrawTriangle(shape0[12], shape0[10], shape0[9], shapeColor0);
        DrawTriangle(shape0[16], shape0[12], shape0[9], shapeColor0);
        DrawTriangle(shape0[18], shape0[16], shape0[9], shapeColor0);
        DrawTriangle(shape0[19], shape0[18], shape0[9], shapeColor0);
        DrawTriangle(shape0[27], shape0[19], shape0[9], shapeColor0);
        DrawTriangle(shape0[28], shape0[27], shape0[9], shapeColor0);
        DrawTriangle(shape0[28], shape0[9], shape0[8], shapeColor0);
        DrawTriangle(shape0[8], shape0[7], shape0[6], shapeColor0);
        DrawTriangle(shape0[8], shape0[6], shape0[5], shapeColor0);
        DrawTriangle(shape0[28], shape0[8], shape0[5], shapeColor0);
        DrawTriangle(shape0[28], shape0[5], shape0[4], shapeColor0);
        DrawTriangle(shape0[28], shape0[4], shape0[3], shapeColor0);
        DrawTriangle(shape0[28], shape0[3], shape0[2], shapeColor0);
        DrawTriangle(shape0[0], shape0[28], shape0[2], shapeColor0);
        DrawTriangle(shape0[2], shape0[1], shape0[0], shapeColor0);
    }
    {
        const Color shapeColor1 = Color{.r = 59, .g = 93, .b = 201, .a = 255};
        const std::array<Vector2, 5> shape1 = {
            at(-1.000F, -0.800F),
            at(-0.800F, -0.600F),
            at(-0.800F, -0.800F),
            at(-0.900F, -0.900F),
            at(-1.000F, -0.900F),
        };
        DrawTriangleFan(shape1.data(), static_cast<int>(shape1.size()), shapeColor1);
    }
    {
        const Color shapeColor2 = Color{.r = 59, .g = 93, .b = 201, .a = 255};
        const std::array<Vector2, 6> shape2 = {
            at(1.000F, -0.900F),
            at(0.900F, -0.900F),
            at(0.800F, -0.800F),
            at(0.800F, -0.600F),
            at(1.000F, -0.800F),
            at(1.000F, -0.900F),
        };
        DrawTriangleFan(shape2.data(), static_cast<int>(shape2.size()), shapeColor2);
    }
    {
        const Color shapeColor3 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 6> shape3 = {
            at(-1.000F, -0.800F),
            at(-1.000F, -0.700F),
            at(-0.900F, -0.600F),
            at(-0.800F, -0.500F),
            at(-0.800F, -0.600F),
            at(-0.900F, -0.700F),
        };
        DrawTriangleFan(shape3.data(), static_cast<int>(shape3.size()), shapeColor3);
    }
    {
        const Color shapeColor4 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 6> shape4 = {
            at(-0.200F, 0.400F),
            at(0.000F, 0.600F),
            at(0.200F, 0.400F),
            at(0.200F, -0.900F),
            at(0.000F, -1.000F),
            at(-0.200F, -0.900F),
        };
        DrawTriangleFan(shape4.data(), static_cast<int>(shape4.size()), shapeColor4);
    }
    {
        const Color shapeColor5 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 7> shape5 = {
            at(-1.300F, 0.300F),
            at(-1.300F, 0.600F),
            at(-1.200F, 0.600F),
            at(-1.100F, 0.500F),
            at(-1.100F, 0.300F),
            at(-1.100F, 0.200F),
            at(-1.200F, 0.200F),
        };
        DrawTriangleFan(shape5.data(), static_cast<int>(shape5.size()), shapeColor5);
    }
    {
        const Color shapeColor6 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 8> shape6 = {
            at(-1.000F, 0.100F),
            at(-1.000F, 0.262F),
            at(-1.000F, 0.400F),
            at(-0.900F, 0.400F),
            at(-0.800F, 0.300F),
            at(-0.800F, 0.100F),
            at(-0.800F, 0.000F),
            at(-0.900F, 0.000F),
        };
        DrawTriangleFan(shape6.data(), static_cast<int>(shape6.size()), shapeColor6);
    }
    {
        const Color shapeColor7 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 4> shape7 = {
            at(-0.700F, 0.200F),
            at(-0.700F, 0.300F),
            at(-0.600F, 0.200F),
            at(-0.600F, 0.100F),
        };
        DrawTriangleFan(shape7.data(), static_cast<int>(shape7.size()), shapeColor7);
    }
    {
        const Color shapeColor8 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 5> shape8 = {
            at(-0.600F, -0.100F),
            at(-0.600F, 0.000F),
            at(-0.700F, 0.100F),
            at(-0.700F, 0.000F),
            at(-0.645F, -0.055F),
        };
        DrawTriangle(shape8[4], shape8[3], shape8[2], shapeColor8);
        DrawTriangle(shape8[0], shape8[4], shape8[2], shapeColor8);
        DrawTriangle(shape8[2], shape8[1], shape8[0], shapeColor8);
    }
    {
        const Color shapeColor9 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 4> shape9 = {
            at(-0.700F, -0.200F),
            at(-0.700F, -0.100F),
            at(-0.600F, -0.200F),
            at(-0.600F, -0.300F),
        };
        DrawTriangleFan(shape9.data(), static_cast<int>(shape9.size()), shapeColor9);
    }
    {
        const Color shapeColor10 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 13> shape10 = {
            at(-0.900F, 0.600F),
            at(-0.800F, 0.600F),
            at(-0.800F, 0.700F),
            at(-0.700F, 0.800F),
            at(-0.700F, 0.900F),
            at(-0.800F, 1.000F),
            at(-0.800F, 0.900F),
            at(-0.800F, 0.800F),
            at(-0.900F, 0.800F),
            at(-0.900F, 1.000F),
            at(-1.000F, 0.900F),
            at(-1.000F, 0.800F),
            at(-0.900F, 0.700F),
        };
        DrawTriangle(shape10[12], shape10[11], shape10[10], shapeColor10);
        DrawTriangle(shape10[10], shape10[9], shape10[8], shapeColor10);
        DrawTriangle(shape10[12], shape10[10], shape10[8], shapeColor10);
        DrawTriangle(shape10[12], shape10[8], shape10[7], shapeColor10);
        DrawTriangle(shape10[0], shape10[12], shape10[7], shapeColor10);
        DrawTriangle(shape10[6], shape10[5], shape10[4], shapeColor10);
        DrawTriangle(shape10[7], shape10[6], shape10[4], shapeColor10);
        DrawTriangle(shape10[0], shape10[7], shape10[4], shapeColor10);
        DrawTriangle(shape10[4], shape10[3], shape10[2], shapeColor10);
        DrawTriangle(shape10[0], shape10[4], shape10[2], shapeColor10);
        DrawTriangle(shape10[2], shape10[1], shape10[0], shapeColor10);
    }
    {
        const Color shapeColor11 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 6> shape11 = {
            at(0.900F, -0.700F),
            at(0.800F, -0.600F),
            at(0.800F, -0.500F),
            at(0.900F, -0.600F),
            at(1.000F, -0.700F),
            at(1.000F, -0.800F),
        };
        DrawTriangleFan(shape11.data(), static_cast<int>(shape11.size()), shapeColor11);
    }
    {
        const Color shapeColor12 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 7> shape12 = {
            at(1.200F, 0.200F),
            at(1.100F, 0.200F),
            at(1.100F, 0.300F),
            at(1.100F, 0.500F),
            at(1.200F, 0.600F),
            at(1.300F, 0.600F),
            at(1.300F, 0.300F),
        };
        DrawTriangleFan(shape12.data(), static_cast<int>(shape12.size()), shapeColor12);
    }
    {
        const Color shapeColor13 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 8> shape13 = {
            at(0.900F, 0.000F),
            at(0.800F, 0.000F),
            at(0.800F, 0.100F),
            at(0.800F, 0.300F),
            at(0.900F, 0.400F),
            at(1.000F, 0.400F),
            at(1.000F, 0.262F),
            at(1.000F, 0.100F),
        };
        DrawTriangleFan(shape13.data(), static_cast<int>(shape13.size()), shapeColor13);
    }
    {
        const Color shapeColor14 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 4> shape14 = {
            at(0.600F, 0.100F),
            at(0.600F, 0.200F),
            at(0.700F, 0.300F),
            at(0.700F, 0.200F),
        };
        DrawTriangleFan(shape14.data(), static_cast<int>(shape14.size()), shapeColor14);
    }
    {
        const Color shapeColor15 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 5> shape15 = {
            at(0.600F, -0.100F),
            at(0.600F, 0.000F),
            at(0.700F, 0.100F),
            at(0.700F, 0.000F),
            at(0.645F, -0.055F),
        };
        DrawTriangle(shape15[2], shape15[3], shape15[4], shapeColor15);
        DrawTriangle(shape15[2], shape15[4], shape15[0], shapeColor15);
        DrawTriangle(shape15[0], shape15[1], shape15[2], shapeColor15);
    }
    {
        const Color shapeColor16 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 4> shape16 = {
            at(0.600F, -0.300F),
            at(0.600F, -0.200F),
            at(0.700F, -0.100F),
            at(0.700F, -0.200F),
        };
        DrawTriangleFan(shape16.data(), static_cast<int>(shape16.size()), shapeColor16);
    }
    {
        const Color shapeColor17 = Color{.r = 26, .g = 28, .b = 44, .a = 255};
        const std::array<Vector2, 13> shape17 = {
            at(0.900F, 0.600F),
            at(0.800F, 0.600F),
            at(0.800F, 0.700F),
            at(0.700F, 0.800F),
            at(0.700F, 0.900F),
            at(0.800F, 1.000F),
            at(0.800F, 0.900F),
            at(0.800F, 0.800F),
            at(0.900F, 0.800F),
            at(0.900F, 1.000F),
            at(1.000F, 0.900F),
            at(1.000F, 0.800F),
            at(0.900F, 0.700F),
        };
        DrawTriangle(shape17[12], shape17[0], shape17[1], shapeColor17);
        DrawTriangle(shape17[12], shape17[1], shape17[2], shapeColor17);
        DrawTriangle(shape17[12], shape17[2], shape17[3], shapeColor17);
        DrawTriangle(shape17[12], shape17[3], shape17[4], shapeColor17);
        DrawTriangle(shape17[4], shape17[5], shape17[6], shapeColor17);
        DrawTriangle(shape17[4], shape17[6], shape17[7], shapeColor17);
        DrawTriangle(shape17[8], shape17[9], shape17[10], shapeColor17);
        DrawTriangle(shape17[8], shape17[10], shape17[11], shapeColor17);
        DrawTriangle(shape17[8], shape17[11], shape17[12], shapeColor17);
        DrawTriangle(shape17[7], shape17[8], shape17[12], shapeColor17);
        DrawTriangle(shape17[4], shape17[7], shape17[12], shapeColor17);
    }
    {
        const Color shapeColor18 = Color{.r = 65, .g = 166, .b = 246, .a = 255};
        const std::array<Vector2, 9> shape18 = {
            at(-0.500F, -0.200F),
            at(-0.400F, -0.400F),
            at(0.000F, -0.700F),
            at(0.400F, -0.400F),
            at(0.500F, -0.200F),
            at(0.500F, 0.100F),
            at(0.100F, -0.200F),
            at(-0.100F, -0.200F),
            at(-0.500F, 0.100F),
        };
        DrawTriangle(shape18[0], shape18[8], shape18[7], shapeColor18);
        DrawTriangle(shape18[6], shape18[5], shape18[4], shapeColor18);
        DrawTriangle(shape18[6], shape18[4], shape18[3], shapeColor18);
        DrawTriangle(shape18[7], shape18[6], shape18[3], shapeColor18);
        DrawTriangle(shape18[0], shape18[7], shape18[3], shapeColor18);
        DrawTriangle(shape18[0], shape18[3], shape18[2], shapeColor18);
        DrawTriangle(shape18[2], shape18[1], shape18[0], shapeColor18);
    }

    // Jets: the two dark thruster nubs at the rear (shape10 at ~(-0.85, 0.8), shape17 at
    // ~(0.85, 0.8)) get an exhaust flame flickering out the back (+Y, away from the nose at -Y).
    const float flicker = 0.65F + 0.35F * std::sin(static_cast<float>(GetTime()) * 28.0F);
    const Color flameOuter = ColorAlpha(Color{.r = 90, .g = 190, .b = 255, .a = 255}, 0.7F + 0.3F * flicker);
    const Color flameInner = ColorAlpha(Color{.r = 225, .g = 245, .b = 255, .a = 255}, 0.9F + 0.1F * flicker);
    for (const float side : {-1.0F, 1.0F})
    {
        const float cx = side * 0.85F;
        const Vector2 left = at(cx - 0.12F, 0.85F);
        const Vector2 right = at(cx + 0.12F, 0.85F);
        const Vector2 tip = at(cx, 0.85F + 0.55F + 0.35F * flicker);
        DrawTriangle(left, tip, right, flameOuter);

        const Vector2 innerLeft = at(cx - 0.06F, 0.85F);
        const Vector2 innerRight = at(cx + 0.06F, 0.85F);
        const Vector2 innerTip = at(cx, 0.85F + 0.35F + 0.2F * flicker);
        DrawTriangle(innerLeft, innerTip, innerRight, flameInner);
    }
}
