#include "ships/interceptor.hpp"

#include "raymath.h"
#include <array>
#include <cmath>

// Generated by tools/svg_to_ship.py from a hand-drawn pixel-art SVG, then wired up here.
// Regenerate with: python3 tools/svg_to_ship.py yourfile.svg
void drawInterceptorHull(Vector2 p, float r, float angle, Color shipColor)
{
    const auto rotate = [angle](Vector2 v) -> Vector2
    {
        const float cosA = std::cos(angle);
        const float sinA = std::sin(angle);
        return Vector2{.x = v.x * cosA - v.y * sinA, .y = v.x * sinA + v.y * cosA};
    };
    const auto at = [&](float x, float y) -> Vector2
    {
        return Vector2Add(p, rotate(Vector2{.x = x * r, .y = y * r}));
    };
    (void)shipColor; // hull uses its own fixed pixel-art palette, not the ship's tint color

    {
        const Color shapeColor0 = Color{.r = 56, .g = 183, .b = 100, .a = 255};
        const std::array<Vector2, 8> shape0 = {
            at(-0.296F, -0.778F),
            at(-0.296F, -1.000F),
            at(-0.222F, -0.926F),
            at(-0.222F, -0.333F),
            at(-0.296F, -0.259F),
            at(-0.296F, -0.333F),
            at(-0.370F, -0.259F),
            at(-0.370F, -0.704F),
        };
        DrawTriangle(shape0[0], shape0[7], shape0[6], shapeColor0);
        DrawTriangle(shape0[0], shape0[6], shape0[5], shapeColor0);
        DrawTriangle(shape0[5], shape0[4], shape0[3], shapeColor0);
        DrawTriangle(shape0[0], shape0[5], shape0[3], shapeColor0);
        DrawTriangle(shape0[0], shape0[3], shape0[2], shapeColor0);
        DrawTriangle(shape0[2], shape0[1], shape0[0], shapeColor0);
    }
    {
        const Color shapeColor1 = Color{.r = 56, .g = 183, .b = 100, .a = 255};
        const std::array<Vector2, 8> shape1 = {
            at(0.296F, -0.778F),
            at(0.296F, -1.000F),
            at(0.222F, -0.926F),
            at(0.222F, -0.333F),
            at(0.296F, -0.259F),
            at(0.296F, -0.333F),
            at(0.370F, -0.259F),
            at(0.370F, -0.704F),
        };
        DrawTriangle(shape1[0], shape1[1], shape1[2], shapeColor1);
        DrawTriangle(shape1[0], shape1[2], shape1[3], shapeColor1);
        DrawTriangle(shape1[7], shape1[0], shape1[3], shapeColor1);
        DrawTriangle(shape1[3], shape1[4], shape1[5], shapeColor1);
        DrawTriangle(shape1[7], shape1[3], shape1[5], shapeColor1);
        DrawTriangle(shape1[5], shape1[6], shape1[7], shapeColor1);
    }
    {
        const Color shapeColor2 = Color{.r = 56, .g = 183, .b = 100, .a = 255};
        const std::array<Vector2, 7> shape2 = {
            at(-0.444F, 0.111F),
            at(-0.444F, 0.407F),
            at(-0.148F, 0.704F),
            at(-0.593F, 0.704F),
            at(-0.741F, 0.704F),
            at(-0.963F, 0.926F),
            at(-0.963F, 0.630F),
        };
        DrawTriangle(shape2[0], shape2[6], shape2[5], shapeColor2);
        DrawTriangle(shape2[0], shape2[5], shape2[4], shapeColor2);
        DrawTriangle(shape2[0], shape2[4], shape2[3], shapeColor2);
        DrawTriangle(shape2[3], shape2[2], shape2[1], shapeColor2);
        DrawTriangle(shape2[3], shape2[1], shape2[0], shapeColor2);
    }
    {
        const Color shapeColor3 = Color{.r = 56, .g = 183, .b = 100, .a = 255};
        const std::array<Vector2, 7> shape3 = {
            at(0.444F, 0.111F),
            at(0.444F, 0.407F),
            at(0.148F, 0.704F),
            at(0.593F, 0.704F),
            at(0.741F, 0.704F),
            at(0.963F, 0.926F),
            at(0.963F, 0.630F),
        };
        DrawTriangle(shape3[6], shape3[0], shape3[1], shapeColor3);
        DrawTriangle(shape3[6], shape3[1], shape3[2], shapeColor3);
        DrawTriangle(shape3[6], shape3[2], shape3[3], shapeColor3);
        DrawTriangle(shape3[6], shape3[3], shape3[4], shapeColor3);
        DrawTriangle(shape3[4], shape3[5], shape3[6], shapeColor3);
    }
    {
        const Color shapeColor4 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape4 = {
            at(-0.370F, -0.704F),
            at(-0.296F, -0.778F),
            at(-0.296F, -0.852F),
            at(-0.370F, -0.778F),
        };
        DrawTriangleFan(shape4.data(), static_cast<int>(shape4.size()), shapeColor4);
    }
    {
        const Color shapeColor5 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape5 = {
            at(-0.370F, -0.556F),
            at(-0.296F, -0.630F),
            at(-0.296F, -0.704F),
            at(-0.370F, -0.630F),
        };
        DrawTriangleFan(shape5.data(), static_cast<int>(shape5.size()), shapeColor5);
    }
    {
        const Color shapeColor6 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape6 = {
            at(-0.370F, -0.407F),
            at(-0.296F, -0.481F),
            at(-0.296F, -0.556F),
            at(-0.370F, -0.481F),
        };
        DrawTriangleFan(shape6.data(), static_cast<int>(shape6.size()), shapeColor6);
    }
    {
        const Color shapeColor7 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape7 = {
            at(-0.370F, -0.259F),
            at(-0.296F, -0.333F),
            at(-0.296F, -0.407F),
            at(-0.370F, -0.333F),
        };
        DrawTriangleFan(shape7.data(), static_cast<int>(shape7.size()), shapeColor7);
    }
    {
        const Color shapeColor8 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape8 = {
            at(0.370F, -0.778F),
            at(0.296F, -0.852F),
            at(0.296F, -0.778F),
            at(0.370F, -0.704F),
        };
        DrawTriangleFan(shape8.data(), static_cast<int>(shape8.size()), shapeColor8);
    }
    {
        const Color shapeColor9 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape9 = {
            at(0.370F, -0.630F),
            at(0.296F, -0.704F),
            at(0.296F, -0.630F),
            at(0.370F, -0.556F),
        };
        DrawTriangleFan(shape9.data(), static_cast<int>(shape9.size()), shapeColor9);
    }
    {
        const Color shapeColor10 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape10 = {
            at(0.370F, -0.481F),
            at(0.296F, -0.556F),
            at(0.296F, -0.481F),
            at(0.370F, -0.407F),
        };
        DrawTriangleFan(shape10.data(), static_cast<int>(shape10.size()), shapeColor10);
    }
    {
        const Color shapeColor11 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape11 = {
            at(0.370F, -0.333F),
            at(0.296F, -0.407F),
            at(0.296F, -0.333F),
            at(0.370F, -0.259F),
        };
        DrawTriangleFan(shape11.data(), static_cast<int>(shape11.size()), shapeColor11);
    }
    {
        const Color shapeColor12 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape12 = {
            at(-0.593F, 0.407F),
            at(-0.519F, 0.407F),
            at(-0.519F, 0.333F),
            at(-0.593F, 0.333F),
        };
        DrawTriangleFan(shape12.data(), static_cast<int>(shape12.size()), shapeColor12);
    }
    {
        const Color shapeColor13 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape13 = {
            at(-0.889F, 0.630F),
            at(-0.889F, 0.704F),
            at(-0.815F, 0.704F),
            at(-0.815F, 0.630F),
        };
        DrawTriangleFan(shape13.data(), static_cast<int>(shape13.size()), shapeColor13);
    }
    {
        const Color shapeColor14 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape14 = {
            at(-0.741F, 0.481F),
            at(-0.741F, 0.556F),
            at(-0.667F, 0.556F),
            at(-0.667F, 0.481F),
        };
        DrawTriangleFan(shape14.data(), static_cast<int>(shape14.size()), shapeColor14);
    }
    {
        const Color shapeColor15 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape15 = {
            at(0.593F, 0.333F),
            at(0.519F, 0.333F),
            at(0.519F, 0.407F),
            at(0.593F, 0.407F),
        };
        DrawTriangleFan(shape15.data(), static_cast<int>(shape15.size()), shapeColor15);
    }
    {
        const Color shapeColor16 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape16 = {
            at(0.815F, 0.630F),
            at(0.815F, 0.704F),
            at(0.889F, 0.704F),
            at(0.889F, 0.630F),
        };
        DrawTriangleFan(shape16.data(), static_cast<int>(shape16.size()), shapeColor16);
    }
    {
        const Color shapeColor17 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 4> shape17 = {
            at(0.667F, 0.481F),
            at(0.667F, 0.556F),
            at(0.741F, 0.556F),
            at(0.741F, 0.481F),
        };
        DrawTriangleFan(shape17.data(), static_cast<int>(shape17.size()), shapeColor17);
    }
    {
        const Color shapeColor18 = Color{.r = 41, .g = 54, .b = 111, .a = 255};
        const std::array<Vector2, 22> shape18 = {
            at(-0.370F, -0.037F),
            at(-0.444F, -0.111F),
            at(-0.222F, -0.333F),
            at(-0.148F, -0.778F),
            at(-0.074F, -0.704F),
            at(0.074F, -0.704F),
            at(0.148F, -0.778F),
            at(0.222F, -0.333F),
            at(0.444F, -0.111F),
            at(0.370F, -0.037F),
            at(0.296F, 0.037F),
            at(0.296F, 0.111F),
            at(0.296F, 0.407F),
            at(0.222F, 0.407F),
            at(0.148F, 0.481F),
            at(0.074F, 0.556F),
            at(-0.074F, 0.556F),
            at(-0.148F, 0.481F),
            at(-0.222F, 0.407F),
            at(-0.296F, 0.407F),
            at(-0.296F, 0.111F),
            at(-0.296F, 0.037F),
        };
        DrawTriangle(shape18[20], shape18[19], shape18[18], shapeColor18);
        DrawTriangle(shape18[21], shape18[20], shape18[18], shapeColor18);
        DrawTriangle(shape18[21], shape18[18], shape18[17], shapeColor18);
        DrawTriangle(shape18[21], shape18[17], shape18[16], shapeColor18);
        DrawTriangle(shape18[21], shape18[16], shape18[15], shapeColor18);
        DrawTriangle(shape18[21], shape18[15], shape18[14], shapeColor18);
        DrawTriangle(shape18[21], shape18[14], shape18[13], shapeColor18);
        DrawTriangle(shape18[0], shape18[21], shape18[13], shapeColor18);
        DrawTriangle(shape18[0], shape18[13], shape18[12], shapeColor18);
        DrawTriangle(shape18[0], shape18[12], shape18[11], shapeColor18);
        DrawTriangle(shape18[0], shape18[11], shape18[10], shapeColor18);
        DrawTriangle(shape18[0], shape18[10], shape18[9], shapeColor18);
        DrawTriangle(shape18[0], shape18[9], shape18[8], shapeColor18);
        DrawTriangle(shape18[0], shape18[8], shape18[7], shapeColor18);
        DrawTriangle(shape18[0], shape18[7], shape18[6], shapeColor18);
        DrawTriangle(shape18[0], shape18[6], shape18[5], shapeColor18);
        DrawTriangle(shape18[4], shape18[3], shape18[2], shapeColor18);
        DrawTriangle(shape18[5], shape18[4], shape18[2], shapeColor18);
        DrawTriangle(shape18[0], shape18[5], shape18[2], shapeColor18);
        DrawTriangle(shape18[2], shape18[1], shape18[0], shapeColor18);
    }
    {
        const Color shapeColor19 = Color{.r = 41, .g = 54, .b = 111, .a = 255};
        const std::array<Vector2, 4> shape19 = {
            at(-0.519F, 0.778F),
            at(-0.296F, 0.778F),
            at(-0.296F, 0.704F),
            at(-0.519F, 0.704F),
        };
        DrawTriangleFan(shape19.data(), static_cast<int>(shape19.size()), shapeColor19);
    }
    {
        const Color shapeColor20 = Color{.r = 41, .g = 54, .b = 111, .a = 255};
        const std::array<Vector2, 4> shape20 = {
            at(0.296F, 0.778F),
            at(0.519F, 0.778F),
            at(0.519F, 0.704F),
            at(0.296F, 0.704F),
        };
        DrawTriangleFan(shape20.data(), static_cast<int>(shape20.size()), shapeColor20);
    }
    {
        const Color shapeColor21 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 6> shape21 = {
            at(-0.519F, 0.481F),
            at(-0.370F, 0.481F),
            at(-0.222F, 0.630F),
            at(-0.593F, 0.630F),
            at(-0.963F, 1.000F),
            at(-0.963F, 0.926F),
        };
        DrawTriangle(shape21[0], shape21[5], shape21[4], shapeColor21);
        DrawTriangle(shape21[0], shape21[4], shape21[3], shapeColor21);
        DrawTriangle(shape21[0], shape21[3], shape21[2], shapeColor21);
        DrawTriangle(shape21[2], shape21[1], shape21[0], shapeColor21);
    }
    {
        const Color shapeColor22 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 20> shape22 = {
            at(-0.074F, 0.704F),
            at(-0.370F, 0.407F),
            at(-0.370F, -0.037F),
            at(-0.296F, 0.037F),
            at(-0.296F, 0.407F),
            at(-0.222F, 0.407F),
            at(-0.222F, -0.926F),
            at(-0.148F, -1.000F),
            at(-0.148F, 0.481F),
            at(-0.074F, 0.556F),
            at(0.074F, 0.556F),
            at(0.148F, 0.481F),
            at(0.148F, -1.000F),
            at(0.222F, -0.926F),
            at(0.222F, 0.407F),
            at(0.296F, 0.407F),
            at(0.296F, 0.037F),
            at(0.370F, -0.037F),
            at(0.370F, 0.407F),
            at(0.074F, 0.704F),
        };
        DrawTriangle(shape22[0], shape22[19], shape22[18], shapeColor22);
        DrawTriangle(shape22[18], shape22[17], shape22[16], shapeColor22);
        DrawTriangle(shape22[18], shape22[16], shape22[15], shapeColor22);
        DrawTriangle(shape22[0], shape22[18], shape22[15], shapeColor22);
        DrawTriangle(shape22[14], shape22[13], shape22[12], shapeColor22);
        DrawTriangle(shape22[14], shape22[12], shape22[11], shapeColor22);
        DrawTriangle(shape22[15], shape22[14], shape22[11], shapeColor22);
        DrawTriangle(shape22[15], shape22[11], shape22[10], shapeColor22);
        DrawTriangle(shape22[0], shape22[15], shape22[10], shapeColor22);
        DrawTriangle(shape22[0], shape22[10], shape22[9], shapeColor22);
        DrawTriangle(shape22[0], shape22[9], shape22[8], shapeColor22);
        DrawTriangle(shape22[8], shape22[7], shape22[6], shapeColor22);
        DrawTriangle(shape22[8], shape22[6], shape22[5], shapeColor22);
        DrawTriangle(shape22[0], shape22[8], shape22[5], shapeColor22);
        DrawTriangle(shape22[0], shape22[5], shape22[4], shapeColor22);
        DrawTriangle(shape22[4], shape22[3], shape22[2], shapeColor22);
        DrawTriangle(shape22[4], shape22[2], shape22[1], shapeColor22);
        DrawTriangle(shape22[4], shape22[1], shape22[0], shapeColor22);
    }
    {
        const Color shapeColor23 = Color{.r = 37, .g = 113, .b = 121, .a = 255};
        const std::array<Vector2, 6> shape23 = {
            at(0.519F, 0.481F),
            at(0.370F, 0.481F),
            at(0.222F, 0.630F),
            at(0.593F, 0.630F),
            at(0.963F, 1.000F),
            at(0.963F, 0.926F),
        };
        DrawTriangle(shape23[0], shape23[1], shape23[2], shapeColor23);
        DrawTriangle(shape23[0], shape23[2], shape23[3], shapeColor23);
        DrawTriangle(shape23[5], shape23[0], shape23[3], shapeColor23);
        DrawTriangle(shape23[3], shape23[4], shape23[5], shapeColor23);
    }
    {
        const Color shapeColor24 = Color{.r = 65, .g = 166, .b = 246, .a = 255};
        const std::array<Vector2, 8> shape24 = {
            at(-0.148F, -0.185F),
            at(-0.148F, -0.481F),
            at(0.000F, -0.630F),
            at(0.148F, -0.481F),
            at(0.148F, -0.185F),
            at(0.074F, -0.185F),
            at(0.000F, -0.259F),
            at(-0.074F, -0.185F),
        };
        DrawTriangle(shape24[0], shape24[7], shape24[6], shapeColor24);
        DrawTriangle(shape24[6], shape24[5], shape24[4], shapeColor24);
        DrawTriangle(shape24[6], shape24[4], shape24[3], shapeColor24);
        DrawTriangle(shape24[0], shape24[6], shape24[3], shapeColor24);
        DrawTriangle(shape24[0], shape24[3], shape24[2], shapeColor24);
        DrawTriangle(shape24[2], shape24[1], shape24[0], shapeColor24);
    }

    // Jets: the two small rear thruster nubs (shape19 at ~(-0.41, 0.74), shape20 at
    // ~(0.41, 0.74)) get an exhaust flame flickering out the back (+Y, away from the nose at -Y),
    // tinted green to match the hull.
    const float flicker = 0.65F + 0.35F * std::sin(static_cast<float>(GetTime()) * 28.0F);
    const Color flameOuter = ColorAlpha(Color{.r = 90, .g = 220, .b = 130, .a = 255}, 0.7F + 0.3F * flicker);
    const Color flameInner = ColorAlpha(Color{.r = 220, .g = 250, .b = 225, .a = 255}, 0.9F + 0.1F * flicker);
    for (const float side : {-1.0F, 1.0F})
    {
        const float cx = side * 0.41F;
        const Vector2 left = at(cx - 0.1F, 0.74F);
        const Vector2 right = at(cx + 0.1F, 0.74F);
        const Vector2 tip = at(cx, 0.74F + 0.55F + 0.35F * flicker);
        DrawTriangle(left, tip, right, flameOuter);

        const Vector2 innerLeft = at(cx - 0.05F, 0.74F);
        const Vector2 innerRight = at(cx + 0.05F, 0.74F);
        const Vector2 innerTip = at(cx, 0.74F + 0.35F + 0.2F * flicker);
        DrawTriangle(innerLeft, innerTip, innerRight, flameInner);
    }
}
